sheepwhite: 4
sheeporange: 2
sheepmagenta: 2
sheeplight_blue: 2
sheepyellow: 2
sheeplime: 2
sheeppink: 2
sheepgray: 2
sheepsilver: 2
sheepcyan: 2
sheeppurple: 2
sheepblue: 2
sheepbrown: 2
sheepgreen: 2
sheepred: 2
sheepblack: 2
chicken: 4
cow: 4
mushroom_cow: 4
ocelot: 4
pig: 4
wolf: 4
blaze: 4
cave_spider: 4
creeper: 4
enderman: 4
pig_zombie: 4
silverfish: 6
skeleton: 4
spider: 4
zombie: 1
agecapbaby: 300
agecapbreed: 300
settings:
  debug:
    limit_spawn: false
    limits: false
    chunk_unload: false
    age_cap: false
    special: false
  limit_natural_spawn: false
  limit_spawner_spawn: false
  spawn_limited: []
